In [8]:
import pandas as pd
df = pd.read_csv('REQ_DATA_NYW_6_UTF8.csv')
scs = list(df['영업소코드'].unique())
len(scs)

458

In [13]:
import requests
apiKey = '329f8acc-619b-4345-bd86-2e19fbd5aca2'
productId = 'PRDTNUM_000000020305'
# for sc in scs:
#     url = 'https://www.bigdata-transportation.kr/api?apiKey={apiKey}&productId={productId}&unitCode={i}&inoutType=1'
#     response = requests.get(url)

url = f'https://www.bigdata-transportation.kr/api?apiKey={apiKey}&productId={productId}&unitCode=101&inoutType=1'
response = requests.get(url)



print(response.text)

{"resultType":"200","msg":"성공했습니다.","result":{"count":48,"laneStatusVO":[{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"0","laneName":"TCS","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"0","laneName":"TCS","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"0","laneName":"TCS","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"0","laneName":"TCS","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"0","laneName":"TCS","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"0","laneName":"TCS","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"0","laneName":"TCS","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"0","laneName":"TCS","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"0","laneName":"TCS","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"0","laneName":"TCS","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"0","laneName":"TCS","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"0","laneName":"TCS","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"0","laneName":"TCS","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"6","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"7","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"8","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"8","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"8","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"8","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"8","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"8","laneName":"hipass","laneCnt":"48"},{"unitName":"서울","unitCode":"101 ","inoutType":"1","inoutName":"출구","laneType":"8","laneName":"hipass","laneCnt":"48"}],"message":"인증키가 유효합니다.","code":"SUCCESS"}}

In [16]:
df = pd.read_csv('TR021900070001-EX_DY1_VDS_RTP_TPSTS_TB-20230924.csv')
df

,SUM_YRMTHDAT,VDS_CD,COCT_CD,TRFFCVLM,OCCPNCY,SPD_AVG,NMLT_CSCNT,REVISN_CSCNT,LAST_CHANGE_DAYHMINSEC
0,20230924,1020VDS01500,1,-1,-1.00,-1.00,0,0,20230925031222
1,20230924,0552VDS01520,1,27640,3.42,110.78,2509,0,20230925031222
2,20230924,0010VDE17900,1,18501,2.12,96.42,2880,0,20230925031222
3,20230924,4000VDS00001,1,35097,7.41,91.44,2848,0,20230925031222
4,20230924,0650VDS02300,1,10546,1.77,112.86,2880,0,20230925031222
...,...,...,...,...,...,...,...,...,...
8228,20230924,0010VDS30340,2,4359,4.52,101.28,1679,1,20230925031222
8229,20230924,0010VDS31680,2,5228,8.46,94.57,1679,1,20230925031222
8230,20230924,0010VDS30640,2,4829,4.45,96.05,1679,1,20230925031222
8231,20230924,0010VDE30301,2,20,0.44,105.32,0,10,20230925031222
8232,20230924,0010VDE29630,2,0,0.00,0.00,1678,2,20230925031222

In [18]:
pd.read_excel('10.+VDS기반+고속도로+지점별+교통+소통+통계+데이터(1일+단위).xlsx')

ImportError: Missing optional dependency 'openpyxl'.  Use pip or conda to install openpyxl.