In [36]:
import pandas as pd
import numpy as np

In [108]:
year = '2022'

In [109]:
meas_ls = pd.read_csv('./seoul/서울시 대기오염 측정항목 정보.csv', encoding='euc-kr')
meas_loc = pd.read_csv('./seoul/서울시 대기오염 측정소 정보.csv', encoding='euc-kr')
meas = pd.read_csv(f'./seoul/AIR_HOUR_{year}.csv')
meas_items = meas_ls[['측정항목 코드', '측정항목 명(줄임 명칭)']]

In [110]:
# 측정소 코드를 기준으로 두 데이터 프레임을 병합합니다.
merged_df = pd.merge(meas, meas_loc[['측정소 코드', '측정소 이름']], on='측정소 코드', how='left')

# '측정항목' 열을 기준으로 두 데이터 프레임을 병합합니다.
merged_df = pd.merge(merged_df, meas_items, left_on='측정항목', right_on='측정항목 코드', how='left')

In [111]:
new_merged_df = merged_df.drop('측정항목 코드', axis=1)
new_merged_df

,측정일시,측정소 코드,측정항목,평균값,측정기 상태,국가 기준초과 구분,지자체 기준초과 구분,측정소 이름,측정항목 명(줄임 명칭)
0,2022010100,101,1,0.003,0,0,0,종로구,SO2
1,2022010100,101,3,0.016,0,0,0,종로구,NO2
2,2022010100,101,5,0.400,0,0,0,종로구,CO
3,2022010100,101,6,0.026,0,0,0,종로구,O3
4,2022010100,101,8,23.000,0,0,0,종로구,PM10
...,...,...,...,...,...,...,...,...,...
1313995,2022123123,125,3,0.054,0,0,0,강동구,NO2
1313996,2022123123,125,5,1.100,0,0,0,강동구,CO
1313997,2022123123,125,6,0.002,0,0,0,강동구,O3
1313998,2022123123,125,8,71.000,0,0,0,강동구,PM10
1313999,2022123123,125,9,57.000,0,1,1,강동구,PM2.5

In [112]:
new_merged_df.to_csv(f'./ch_seoul/new_AIR_HOUR_{year}.csv', encoding='utf-8-sig')